### ISSUE TITLE
добавить возможность удаления/скрытия из списка пользователей

### ISSUE THREAD

**Issue by wsmengine** [mexes-s/WSM#5]

**Comment by mexes-s** [comment]
Предлагаю реализацию: под таблицей разместить панель с кнопками, добавить на нее кнопки для удаления, восстановления выделенного пользователя (это мне пригодится для тестирования, чтобы не создавать каждый раз кучу аккаунтов) и обновления данных. Также пользователь, аккаунт которого был удален, не сможет авторизоваться в систему, пока его не восстановят. Над таблицей также будет добавлена галочка-фильтр "Отображать удаленных пользователей". По сути, удаленный пользователь = заблокированный
